galaxy_info:
  author: Yoann Le Garff
  description: https://github.com/le-garff-yoann/vagrant-k8s
  # company: your company (optional)

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - 10

  galaxy_tags: []

dependencies: []
