---
- name: Generate and apply CoreDNS k8s manifest
  block:
    - tempfile: # noqa 502
      register: tempfile
      changed_when: False

    - template: # noqa 502
        src: coredns.definition.j2
        dest: "{{ tempfile.path }}"

    - command: kubectl apply -f {{ tempfile.path }} # noqa 502
      changed_when: False
  always:
    - file: # noqa 502
        path: "{{ tempfile.path }}"
        state: absent
      changed_when: False
