---
- block:
    - import_tasks: downloads.yml

    - import_tasks: base.yml

    - import_tasks: kubectl.yml

    - import_tasks: kube-apiserver.yml
      when: "'k8s_masters' in group_names"

    - import_tasks: kube-controller-manager.yml
      when: "'k8s_masters' in group_names"

    - import_tasks: kube-scheduler.yml
      when: "'k8s_masters' in group_names"

    - import_tasks: keepalived.yml
      when: "'k8s_masters' in group_names"

    - import_tasks: haproxy.yml
      when: "'k8s_masters' in group_names"

    - import_tasks: kube-proxy.yml

    - import_tasks: kubelet.yml

    - meta: flush_handlers

    - import_tasks: cluster-configuration.yml
      run_once: True
      delegate_to: "{{ groups['k8s_masters'] | first }}"
  always:
    - import_tasks: cleanup.yml
