---
- name: Setup k8s
  import_tasks: k8s.yml

- name: Wait for k8s to be reachable on {{ k8s_config._virtual.vip }}:443
  wait_for:
    host: "{{ k8s_config._virtual.vip }}"
    port: 443

- name: Setup CoreDNS on k8s
  import_tasks: coredns.yml

- name: Setup NFS dynamic storage on k8s
  import_tasks: nfs-dynamic-storage.yml

- name: Setup Traefik v1 on k8s
  import_tasks: traefik1.yml

- name: Setup Helm v2 on k8s
  import_tasks: helm2.yml
