---
- name: Generate and apply NFS k8s manifest
  block:
    - file: # noqa 502
        path: "{{ k8s_config.k8s.services.nfs.hostPath }}"
        state: directory

    - tempfile: # noqa 502
      register: tempfile
      changed_when: False

    - template: # noqa 502
        src: nfs-dynamic-storage.definition.j2
        dest: "{{ tempfile.path }}"

    - command: kubectl apply -f {{ tempfile.path }} # noqa 502
      changed_when: False
  always:
    - file: # noqa 502
        path: "{{ tempfile.path }}"
        state: absent
      changed_when: False
  when: k8s_config.k8s.services.nfs.storageNode == ansible_hostname
