---
srvkube:
  host: .staging
  guest: /srv/kubernetes
virtual:
  domain: virtual.local
  nodes:
    count: 3
    cpus: 2
    memory: 3096
k8s:
  version: 1.17.0
  domain: cluster.local
  etcd:
    version: 3.4.4
  flannel:
    version: 0.9.1
    subnetlen: 24
  pod:
    network: 10.2.0.0/16
  service:
    range: 10.3.0.0/24
    nodePortRange: 30000-40000
    cloudProvider: ""
  services:
    kubeapi:
      ip: 10.3.0.1
    coredns:
      ip: 10.3.0.10
      version: 1.6.7
    nfs:
      version: 2.3.0
      storageNode: k8s1
      hostPath: /srv/nfs
    traefik1:
      version: 1.7.21
      etcdNode: k8s1
      nodePort:
        http: 30001
        https: 30002
  helm2:
    version: 2.16.3
