---
- name: Get Docker apt key
  apt_key:
    id: 0EBFCD88
    url: "{{ container_fabric_docker_repo_download_url }}/gpg"
    validate_certs: no

- name: Setup Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] {{ container_fabric_docker_repo_download_url }} {{ ansible_distribution_release }} stable"

- name: Install docker-ce
  apt:
    name: docker-ce
    update_cache: yes
  notify: Restart docker service

- name: Configure Execstart for integration with flannel in /lib/systemd/system/docker.service
  replace:
    dest: /lib/systemd/system/docker.service
    regexp: "^ExecStart=/usr/bin/dockerd(.*)-H fd://$"
    replace: 'ExecStart=/usr/bin/dockerd\1-H fd:// {{ item }}'
  notify: Restart docker service
  with_items:
    - "--storage-driver=overlay2 --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU} --iptables=false --ip-masq=false --ip-forward=true"

- name: Configure EnvronmentFile for integration with flannel in /lib/systemd/system/docker.service
  lineinfile:
    dest: /lib/systemd/system/docker.service
    line: EnvironmentFile=/run/flannel/subnet.env
    insertafter: '^\[Service\]$'
  notify: Restart docker service

- name: Start the docker service
  systemd:
    name: docker
    daemon_reload: yes
    enabled: yes
    state: started
