---

- hosts: all

  tasks:
    - name: Configure kernel parameters
      block:
        - sysctl:
            name: vm.max_map_count
            value: "262144"
        - sysctl:
            name: "{{ item }}"
            value: "1"
          with_items:
            - net.ipv4.ip_forward
            - net.ipv4.conf.all.forwarding
            - net.ipv4.ip_nonlocal_bind
            - net.ipv6.conf.all.disable_ipv6
            - net.ipv6.conf.default.disable_ipv6
            - net.ipv6.conf.lo.disable_ipv6

    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: False

    - name: Install packages
      apt:
        pkg: "{{ item }}"
        state: latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - git
        - wget
        - curl
        - vim

    - name: Add nodes to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ item.value.ip }} {{ item.key }}.{{ config.virtual.domain }} {{ item.key }}"
      with_dict: "{{ config.virtual.nodes }}"

    - name: Add k8s-etcd and k8s-api to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ item.ip }} {{ item.hostname }}.{{ config.virtual.domain }} {{ item.hostname }}"
      with_items:
        - hostname: k8s-etcd
          ip: "{{ config.k8s.vip }}"
        - hostname: k8s-api
          ip: "{{ config.k8s.vip }}"

    - name: Configure /etc/resolv.conf
      lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
      with_items:
        - nameserver 8.8.8.8
        - search {{ config.virtual.domain }}
