---

- hosts: all

  tasks:
    - name: Generate and apply CoreDNS k8s manifest
      block:
        - tempfile:
            state: file
          register: tempfile
          changed_when: false
        - copy:
            dest: "{{ tempfile.path }}"
            content: |
              ---
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: coredns
                namespace: kube-system

              ---
              apiVersion: rbac.authorization.k8s.io/v1beta1
              kind: ClusterRole
              metadata:
                labels:
                  kubernetes.io/bootstrapping: rbac-defaults
                name: system:coredns
              rules:
                - apiGroups:
                    - ""
                  resources:
                    - endpoints
                    - services
                    - pods
                    - namespaces
                  verbs:
                    - list
                    - watch

              ---
              apiVersion: rbac.authorization.k8s.io/v1beta1
              kind: ClusterRoleBinding
              metadata:
                name: system:coredns
                annotations:
                  rbac.authorization.kubernetes.io/autoupdate: true
                labels:
                  kubernetes.io/bootstrapping: rbac-defaults
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: system:coredns
              subjects:
                - kind: ServiceAccount
                  name: coredns
                  namespace: kube-system

              ---
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: coredns
                namespace: kube-system
              data:
                Corefile: |
                  .:53 {
                      errors
                      log
                      health
                      kubernetes {{ project_config.k8s.domain }} {{ project_config.k8s.service.range }} {{ project_config.k8s.pod.network }} {
                        pods insecure
                        upstream /etc/resolv.conf
                      }
                      prometheus :9153
                      proxy . /etc/resolv.conf
                      cache 30
                  }

              ---
              apiVersion: v1
              kind: Service
              metadata:
                name: coredns
                namespace: kube-system
                labels:
                  app: coredns
                  kubernetes.io/cluster-service: "true"
                  kubernetes.io/name: CoreDNS
                  prometheus.io/port: "9153"
                  prometheus.io/scrape: "true"
              spec:
                selector:
                  app: coredns
                clusterIP: {{ project_config.k8s.services.coredns.ip }}
                ports:
                  - name: dns
                    port: 53
                    protocol: UDP
                  - name: dns-tcp
                    port: 53
                    protocol: TCP
                  - name: metrics
                    port: 9153
                    protocol: TCP

              ---
              apiVersion: extensions/v1beta1
              kind: Deployment
              metadata:
                name: coredns
                namespace: kube-system
                labels:
                  app: coredns
                  kubernetes.io/cluster-service: "true"
                  kubernetes.io/name: CoreDNS
              spec:
                replicas: 1
                strategy:
                  rollingUpdate:
                    maxSurge: 1
                    maxUnavailable: 1
                selector:
                  matchLabels:
                    app: coredns
                template:
                  metadata:
                    labels:
                      app: coredns
                  spec:
                    serviceAccountName: coredns
                    tolerations:
                      - key: node-role.kubernetes.io/master
                        effect: NoSchedule
                      - key: CriticalAddonsOnly
                        operator: Exists
                    affinity:
                      podAntiAffinity:
                        preferredDuringSchedulingIgnoredDuringExecution:
                          - weight: 100
                            podAffinityTerm:
                              labelSelector:
                                matchExpressions:
                                  - key: app
                                    operator: In
                                    values:
                                      - coredns
                              topologyKey: kubernetes.io/hostname
                    containers:
                      - name: coredns
                        image: coredns/coredns:{{ project_config.k8s.services.coredns.version }}
                        imagePullPolicy: IfNotPresent
                        args:
                          - -conf
                          - /etc/coredns/Corefile
                        volumeMounts:
                          - name: config-volume
                            mountPath: /etc/coredns
                        ports:
                          - containerPort: 53
                            protocol: UDP
                          - containerPort: 53
                            protocol: TCP
                          - containerPort: 9153
                            protocol: TCP
                        livenessProbe:
                          httpGet:
                            path: /health
                            port: 8080
                            scheme: HTTP
                          initialDelaySeconds: 60
                          timeoutSeconds: 5
                          successThreshold: 1
                          failureThreshold: 5
                    dnsPolicy: Default
                    volumes:
                      - name: config-volume
                        configMap:
                          name: coredns
                          items:
                            - key: Corefile
                              path: Corefile
        - command: kubectl apply -f {{ tempfile.path }}
          changed_when: false
      always:
        - file:
            path: "{{ tempfile.path }}"
            state: absent
          changed_when: false

    - name: Generate and apply Traefik k8s manifest
      block:
        - tempfile:
            state: file
          register: tempfile
          changed_when: false
        - shell: kubectl create secret generic traefik-cert --from-file='{{ project_config.srvkube.guest }}/traefik.crt' --from-file='{{ project_config.srvkube.guest }}/traefik.key' --namespace=kube-system --dry-run -o yaml | kubectl apply -f -
          changed_when: false
        - copy:
            dest: "{{ tempfile.path }}"
            content: |
              ---
              kind: ClusterRole
              apiVersion: rbac.authorization.k8s.io/v1beta1
              metadata:
                name: traefik
              rules:
                - apiGroups:
                    - ""
                  resources:
                    - pods
                    - services
                    - endpoints
                    - secrets
                  verbs:
                    - get
                    - list
                    - watch
                - apiGroups:
                    - extensions
                  resources:
                    - ingresses
                  verbs:
                    - get
                    - list
                    - watch

              ---
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: traefik
                namespace: kube-system

              ---
              kind: ClusterRoleBinding
              apiVersion: rbac.authorization.k8s.io/v1beta1
              metadata:
                name: traefik
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: traefik
              subjects:
                - kind: ServiceAccount
                  name: traefik
                  namespace: kube-system

              ---
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: traefik
                namespace: kube-system
              data:
                traefik.toml: |
                  defaultEntryPoints = ["https"]
                  insecureSkipVerify = true
                  logLevel = "INFO"

                  [entryPoints]
                    [entryPoints.https]
                    address = ":443"
                    [entryPoints.https.tls]
                    [[entryPoints.https.tls.certificates]]
                    CertFile = "/ssl/traefik.crt"
                    KeyFile = "/ssl/traefik.key"

                  [kubernetes]

                  [web]
                  address = ":8080"
                  readOnly = true

              ---
              kind: Service
              apiVersion: v1
              metadata:
                name: traefik-ingress
                namespace: kube-system
              spec:
                selector:
                  app: traefik
                ports:
                  - name: https
                    protocol: TCP
                    port: 443
                    nodePort: {{ project_config.k8s.services.traefik.nodePort.https }}
                type: NodePort

              ---
              kind: Service
              apiVersion: v1
              metadata:
                name: traefik-dashboard
                namespace: kube-system
              spec:
                selector:
                  app: traefik
                ports:
                  - name: admin
                    protocol: TCP
                    port: 8080

              ---
              apiVersion: extensions/v1beta1
              kind: Ingress
              metadata:
                name: traefik-dashboard-ingress
                namespace: kube-system
              spec:
                rules:
                  - http:
                      paths:
                        - path: /
                          backend:
                            serviceName: traefik-dashboard
                            servicePort: 8080

              ---
              kind: Deployment
              apiVersion: extensions/v1beta1
              metadata:
                name: traefik
                namespace: kube-system
                labels:
                  app: traefik
              spec:
                replicas: 1
                revisionHistoryLimit: 1
                selector:
                  matchLabels:
                    app: traefik
                strategy:
                  type: RollingUpdate
                  rollingUpdate:
                    maxUnavailable: 0
                    maxSurge: 1
                template:
                  metadata:
                    labels:
                      app: traefik
                      name: traefik
                  spec:
                    serviceAccountName: traefik
                    terminationGracePeriodSeconds: 60
                    volumes:
                      - name: config
                        configMap:
                          name: traefik
                      - name: ssl
                        secret:
                          secretName: traefik-cert
                    containers:
                      - image: traefik:{{ project_config.k8s.services.traefik.version }}
                        name: traefik
                        imagePullPolicy: Always
                        resources:
                          limits:
                            cpu: 200m
                            memory: 30Mi
                          requests:
                            cpu: 100m
                            memory: 20Mi
                        volumeMounts:
                          - name: "config"
                            mountPath: "/config"
                          - name: "ssl"
                            mountPath: "/ssl"
                        ports:
                          - containerPort: 443
                          - containerPort: 8080
                        args:
                          - --web
                          - --kubernetes
                          - --configfile=/config/traefik.toml
        - command: kubectl apply -f {{ tempfile.path }}
          changed_when: false
      always:
        - file:
            path: "{{ tempfile.path }}"
            state: absent
          changed_when: false
