---
- name: kubectl set-cluster for {{ k8s_kubeconfig_component }} kubeconfig
  command: >-
    {{ (k8s_binaries_path + '/kubectl') | quote }}
    config set-cluster k8s.{{ ansible_domain }}
    {% if k8s_kubeconfig_component_kubeconfig is defined %}
    --kubeconfig={{ k8s_kubeconfig_component_kubeconfig | quote }}
    {% endif %}
    --user={{ k8s_kubeconfig_component | quote }}
    --certificate-authority={{ k8s_kubeconfig_component_cacerfile | quote }}
    --embed-certs=true
    --server=https://{{ k8s_masters_vip_name }}.{{ ansible_domain }}
  changed_when: False

- name: kubectl set-credentials for {{ k8s_kubeconfig_component }} kubeconfig
  command: >-
    {{ (k8s_binaries_path + '/kubectl') | quote }}
    config set-credentials {{ k8s_kubeconfig_component | quote }}
    {% if k8s_kubeconfig_component_kubeconfig is defined %}
    --kubeconfig={{ k8s_kubeconfig_component_kubeconfig | quote }}
    {% endif %}
    --user={{ k8s_kubeconfig_component | quote }}
    --client-certificate={{ k8s_kubeconfig_component_cerfile | quote }}
    --client-key={{ k8s_kubeconfig_component_keyfile | quote }}
    --embed-certs=true
  changed_when: False

- name: kubectl set-context for {{ k8s_kubeconfig_component }} kubeconfig
  command: >-
    {{ (k8s_binaries_path + '/kubectl') | quote }}
    config set-context k8s.{{ ansible_domain }}
    {% if k8s_kubeconfig_component_kubeconfig is defined %}
    --kubeconfig={{ k8s_kubeconfig_component_kubeconfig | quote }}
    {% endif %}
    --user={{ k8s_kubeconfig_component | quote }}
    --cluster=k8s.{{ ansible_domain }}
  changed_when: False

- name: kubectl use-context for {{ k8s_kubeconfig_component }} kubeconfig
  command: >-
    {{ (k8s_binaries_path + '/kubectl') | quote }}
    config use-context k8s.{{ ansible_domain }}
    {% if k8s_kubeconfig_component_kubeconfig is defined %}
    --kubeconfig={{ k8s_kubeconfig_component_kubeconfig | quote }}
    {% endif %}
    --user={{ k8s_kubeconfig_component | quote }}
  changed_when: False
