---
- name: Configure kernel parameter vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: "262144"

- name: Configure bolean type kernel parameters
  sysctl:
    name: "{{ item }}"
    value: "1"
  with_items:
    - net.ipv4.ip_forward
    - net.ipv4.conf.all.forwarding
    - net.ipv4.ip_nonlocal_bind
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Install packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - git
      - wget
      - curl
      - vim
    update_cache: yes

- name: Add nodes to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.value }} {{ item.key }}.{{ k8s_config.virtual.domain }} {{ item.key }}"
  with_dict: "{{ k8s_config._virtual.inventory }}"

- name: Add k8s-etcd and k8s-api to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}.{{ k8s_config.virtual.domain }} {{ item.hostname }}"
  with_items:
    - hostname: k8s-etcd
      ip: "{{ k8s_config._virtual.vip }}"
    - hostname: k8s-api
      ip: "{{ k8s_config._virtual.vip }}"

- name: Configure /etc/resolv.conf
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
  with_items:
    - nameserver 8.8.8.8
    - search {{ k8s_config.virtual.domain }}
