---
- name: Configure iptables FORWARD ACCEPT
  iptables:
    chain: FORWARD
    policy: ACCEPT

- name: Set flannel configuration in etcd for flannel master node
  command: >-
    etcdctl set /coreos.com/network/config
    '{ "Network": "{{ k8s_config.k8s.pod.network }}", "SubnetLen": {{ k8s_config.k8s.flannel.subnetlen }}, "Backend": { "Type": "vxlan" }}'
  environment:
    ETCDCTL_API: "2"
  changed_when: False

- stat: # noqa 502
    path: /usr/local/bin/flanneld
  register: sym

- command: /usr/local/bin/flanneld --version # noqa 502
  register: flannel_actual_version
  changed_when: False
  when: sym.stat.exists

- name: Download and install flanneld binary
  get_url:
    url: https://github.com/coreos/flannel/releases/download/v{{ k8s_config.k8s.flannel.version }}/flanneld-amd64
    dest: /usr/local/bin/flanneld
  notify: Restart flannel service
  when: not sym.stat.exists or flannel_actual_version.stdout is not search("v" + k8s_config.k8s.flannel.version)

- name: Set permissions on flanneld binary
  file:
    path: /usr/local/bin/flanneld
    mode: 0755

- name: Setup flannel systemd service unit
  template:
    src: flanneld.service.j2
    dest: /lib/systemd/system/flanneld.service
  notify:
    - Restart flannel service
    - Restart docker service

- name: Start flannel service
  systemd:
    name: flanneld
    daemon_reload: yes
    enabled: yes
    state: started
